### ISSUE TITLE
The Parameter is Incorrect

### ISSUE THREAD

**Issue by aquint-g** [SaturnsVoid/GoLANG-Google-Chrome-Password-Recovery#2]
Hi, I've been using this lib for some time.
However, since now, it throws an error : **The Parameter is Incorrect** .

After digging a little bit, it comes from the Crypt32.dll used in the Decrypt function. 

I'm currently trying to fix it but I'm far from experienced with DLLs

**Comment by aquint-g** [comment]
https://hothardware.com/news/google-chrome-aes-256-password-encryption-malware-devs#:~:text=Starting%20with%20Chrome%2080%2C%20the,of%20protection%20for%20added%20security.

**Comment by KingG0ph3r** [comment]
https://github.com/SaturnsVoid/Chrome-Password-Recovery/pull/3
